### ISSUE TITLE
about maven-wrapper, link to current documentation

### ISSUE THREAD

**Issue by xenoterracide** [takari/directory-watcher#13]
It's nice to see that this is now maintained by maven, but googling maven wrapper still brings us to your readme, which links to source, but no current documentation. My apologies for putting this here, I don't have another good way to contact you. Also maybe a very quick migration guide?

**Comment by jvanzyl** [comment]
If you're referring to the Maven Wrapper @mosabua is trying to keep the transition notes here https://github.com/takari/maven-wrapper in the README. The Wrapper will be integrated into 3.7.0.
